packages:
  - apps/*

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - arm64
  libc:
    - current
    - musl

onlyBuiltDependencies:
  - esbuild
  - sharp
allowBuilds:
  esbuild: true
  sharp: true
